version: '3'

services:
    mongodb:
        image: mongo:latest
        ports:
            - '27017:27017'
        volumes:
            - mongodb_data:/data/db
        networks:
            - my-network

    redis-server:
        image: redis:latest
        ports:
            - '6379:6379'
        networks:
            - my-network

    express:
        build: .
        ports:
            - '8000:8000'
        depends_on:
            - mongodb
            - redis-server
        networks:
            - my-network

volumes:
    mongodb_data:

networks:
    my-network:
        driver: bridge
